INSERT INTO products(title, quantity, delivery_fee, description, type, image_url, price) 
VALUES('Demo T-shirt', 10, 12.33, 'Lorem ipsum', 'tshirts', "/images/tshirts/grey.png", 344.44);
INSERT INTO products(title, quantity, delivery_fee, description, type, image_url, price) 
VALUES('Demo T-shirt', 10, 12.33, 'Lorem ipsum', 'tshirts', "/images/tshirts/grey.png", 344.44);
INSERT INTO products(title, quantity, delivery_fee, description, type, image_url, price) 
VALUES('Demo T-shirt', 10, 12.33, 'Lorem ipsum', 'tshirts', "/images/tshirts/grey.png", 344.44);
INSERT INTO products(title, quantity, delivery_fee, description, type, image_url, price) 
VALUES('Demo T-shirt', 10, 12.33, 'Lorem ipsum', 'tshirts', "/images/tshirts/grey.png", 344.44);
INSERT INTO products(title, quantity, delivery_fee, description, type, image_url, price) 
VALUES('Demo T-shirt', 10, 12.33, 'Lorem ipsum', 'tshirts', "/images/tshirts/grey.png", 344.44);
INSERT INTO products(title, quantity, delivery_fee, description, type, image_url, price) 
VALUES('Demo T-shirt', 10, 12.33, 'Lorem ipsum', 'tshirts', "/images/tshirts/grey.png", 344.44);
INSERT INTO products(title, quantity, delivery_fee, description, type, image_url, price) 
VALUES('Demo T-shirt', 10, 12.33, 'Lorem ipsum', 'tshirts', "/images/tshirts/grey.png", 344.44);
INSERT INTO products(title, quantity, delivery_fee, description, type, image_url, price) 
VALUES('Demo T-shirt', 10, 12.33, 'Lorem ipsum', 'tshirts', "/images/tshirts/grey.png", 344.44);
INSERT INTO products(title, quantity, delivery_fee, description, type, image_url, price) 
VALUES('Demo T-shirt', 10, 12.33, 'Lorem ipsum', 'tshirts', "/images/tshirts/grey.png", 344.44);
INSERT INTO products(title, quantity, delivery_fee, description, type, image_url, price) 
VALUES('Demo T-shirt', 10, 12.33, 'Lorem ipsum', 'tshirts', "/images/tshirts/grey.png", 344.44);
INSERT INTO products(title, quantity, delivery_fee, description, type, image_url, price) 
VALUES('Demo T-shirt', 10, 12.33, 'Lorem ipsum', 'tshirts', "/images/tshirts/grey.png", 344.44);
INSERT INTO products(title, quantity, delivery_fee, description, type, image_url, price) 
VALUES('Demo T-shirt', 10, 12.33, 'Lorem ipsum', 'tshirts', "/images/tshirts/grey.png", 344.44);